In [25]:
import numpy as np
np.random.seed(42)
hours_studied=np.random.randint(1,10, size=50)
attendance=np.random.randint(50,100, size=50)
previous=np.random.randint(40,95,size=50)
predicted=(hours_studied*5)+(attendance*0.3)+(previous*0.5)
dataset=np.column_stack([hours_studied, attendance, previous, predicted])
print(dataset)

[[  7.   53.   78.   89.9]
 [  4.   51.   80.   75.3]
 [  8.   55.   67.   90. ]
 [  5.   91.   46.   75.3]
 [  7.   53.   48.   74.9]
 [  3.   78.   47.   61.9]
 [  7.   67.   51.   80.6]
 [  8.   75.   73.   99. ]
 [  5.   93.   72.   88.9]
 [  4.   83.   87.   88.4]
 [  8.   59.   94.  104.7]
 [  8.   85.   62.   96.5]
 [  3.   63.   63.   65.4]
 [  6.   80.   76.   92. ]
 [  5.   97.   74.   91.1]
 [  2.   64.   83.   70.7]
 [  8.   57.   79.   96.6]
 [  6.   63.   61.   79.4]
 [  2.   72.   66.   64.6]
 [  5.   89.   74.   88.7]
 [  1.   70.   40.   46. ]
 [  6.   65.   74.   86.5]
 [  9.   94.   76.  111.2]
 [  1.   67.   86.   68.1]
 [  3.   96.   53.   70.3]
 [  7.   73.   42.   77.9]
 [  4.   75.   40.   62.5]
 [  9.   74.   44.   89.2]
 [  3.   94.   65.   75.7]
 [  5.   90.   94.   99. ]
 [  3.   78.   53.   64.9]
 [  7.   64.   78.   93.2]
 [  5.   94.   66.   86.2]
 [  9.   50.   48.   84. ]
 [  7.   74.   54.   84.2]
 [  2.   56.   54.   53.8]
 [  4.   58.   65.   69.9]
 

In [27]:
import numpy as np
rng=np.random.default_rng(seed=42)
hours_studied=rng.integers(1,10, size=50)
attendance=rng.integers(50,100, size=50)
previous=rng.integers(40,95,size=50)
predicted=(hours_studied*5)+(attendance*0.3)+(previous*0.5)
dataset=np.column_stack([hours_studied, attendance, previous, predicted])
print(dataset)

[[  1.   87.   85.   73.6]
 [  7.   59.   50.   77.7]
 [  6.   68.   84.   92.4]
 [  4.   73.   40.   61.9]
 [  4.   74.   83.   83.7]
 [  8.   52.   83.   97.1]
 [  1.   77.   82.   69.1]
 [  7.   57.   76.   90.1]
 [  2.   87.   65.   68.6]
 [  1.   84.   78.   69.2]
 [  5.   96.   55.   81.3]
 [  9.   87.   82.  112.1]
 [  7.   68.   70.   90.4]
 [  7.   98.   65.   96.9]
 [  7.   70.   67.   89.5]
 [  8.   66.   71.   95.3]
 [  5.   95.   42.   74.5]
 [  2.   68.   47.   53.9]
 [  8.   53.   53.   82.4]
 [  5.   73.   46.   69.9]
 [  5.   89.   64.   83.7]
 [  4.   59.   76.   75.7]
 [  2.   73.   75.   69.4]
 [  9.   56.   65.   94.3]
 [  8.   84.   87.  108.7]
 [  6.   73.   71.   87.4]
 [  4.   66.   44.   61.8]
 [  8.   61.   82.   99.3]
 [  5.   78.   71.   83.9]
 [  4.   83.   74.   81.9]
 [  5.   97.   71.   89.6]
 [  3.   71.   70.   71.3]
 [  1.   58.   44.   44.4]
 [  5.   91.   70.   87.3]
 [  8.   81.   83.  105.8]
 [  1.   85.   56.   58.5]
 [  8.   54.   73.   92.7]
 